import argparse
import html
from pathlib import Path
import sys


def read_text(input_path: str) -> str:
    if input_path:
        return Path(input_path).read_text(encoding="utf-8")
    return sys.stdin.read()


def convert_lines_to_html_blocks(text: str) -> str:
    blocks = []
    in_list = False
    for raw_line in text.replace("\r\n", "\n").split("\n"):
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            if in_list:
                blocks.append("</ul>")
                in_list = False
            continue
        if stripped.startswith("# "):
            if in_list:
                blocks.append("</ul>")
                in_list = False
            blocks.append(f"<h1>{html.escape(stripped[2:].strip())}</h1>")
            continue
        if stripped.startswith("## "):
            if in_list:
                blocks.append("</ul>")
                in_list = False
            blocks.append(f"<h2>{html.escape(stripped[3:].strip())}</h2>")
            continue
        if stripped.startswith("### "):
            if in_list:
                blocks.append("</ul>")
                in_list = False
            blocks.append(f"<h3>{html.escape(stripped[4:].strip())}</h3>")
            continue
        if stripped.startswith(("- ", "* ")):
            if not in_list:
                blocks.append("<ul>")
                in_list = True
            blocks.append(f"<li>{html.escape(stripped[2:].strip())}</li>")
            continue
        if in_list:
            blocks.append("</ul>")
            in_list = False
        blocks.append(f"<p>{html.escape(stripped)}</p>")
    if in_list:
        blocks.append("</ul>")
    return "\n".join(blocks)


def build_html(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{html.escape(title)}</title>
  <style>
    body {{
      font-family: "Microsoft YaHei", "PingFang SC", sans-serif;
      color: #1f2937;
      max-width: 900px;
      margin: 0 auto;
      padding: 48px 40px 72px;
      line-height: 1.8;
      background: #ffffff;
    }}
    h1, h2, h3 {{ line-height: 1.35; }}
    h1 {{ font-size: 30px; margin: 0 0 20px; }}
    h2 {{ font-size: 23px; margin: 28px 0 14px; }}
    h3 {{ font-size: 18px; margin: 20px 0 10px; }}
    p, li {{ font-size: 15px; }}
    ul {{ padding-left: 24px; }}
    .meta {{ color: #6b7280; font-size: 12px; margin-bottom: 28px; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  <div class="meta">Generated by Lmentor artifact-forge</div>
  {body}
</body>
</html>
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="")
    parser.add_argument("--output", required=True)
    parser.add_argument("--title", default="Lmentor Report")
    args = parser.parse_args()

    text = read_text(args.input)
    body = convert_lines_to_html_blocks(text)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_html(args.title, body), encoding="utf-8")
    print(str(output.resolve()))


if __name__ == "__main__":
    main()

